version: 2
updates:
  # Enable version updates for Gradle dependencies in root directory
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Enable version updates for Gradle dependencies in buildSrc directory
  - package-ecosystem: "gradle"
    directory: "/buildSrc"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
