name: Qodana
on: push

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.0.4 #latest versions require connectivity to the cloud